name: water_drop_nav_bar
description: Bottom navigation bar. It has unique water drop effect. Indicates with filled icon.
version: 1.0.0
repository: https://github.com/watery-desert/water_drop_nav_bar

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true